name: Kodexa CLI Python Package

permissions: write-all

on:
  push:
    branches:
      - 'main'

jobs:
  build: 
    name: Package & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: Increment version
        run: poetry version prerelease
      - name: Install dependencies
        run: poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          yes | poetry run mypy --install-types kodexa_cli || true
      - name: Test with pytest
        run: |
          poetry run pytest
      - name: Build Package
        run: |
          poetry build
      - name: Publish a Python distribution to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
      - name: Commit new version
        run: |
          status=$(git status)
          if [[ "$status" == *"nothing to commit"* ]]; then
            echo "Nothing to commit"
          else
            git config --global user.email "helm-docs@github-action.com"
            git config --global user.name "helm-docs"
            git add pyproject.toml
            git commit -m "Update version"  -m "[skip ci]"
            git push
          fi